Fix/persona bug
DimensionDev/Mask-iOS pull request #120
Opened 2022-04-20 08:45 UTC by sxiaojian88

2022-04-20 08:48 UTC, jk234ert requested changes

2022-04-20 08:48 UTC, jk234ert commented on Maskbook/Resources/zh-Hans.lproj/Localizable.strings
> +"Common.Alert.OnlyScanPersona.Title" = "";
Are these localizable strings removed by accident?

2022-04-20 08:49 UTC, sxiaojian88 commented on Maskbook/Resources/zh-Hans.lproj/Localizable.strings
> +"Common.Alert.OnlyScanPersona.Title" = "";
No，I just execute updateLocalization

2022-04-21 07:00 UTC, jk234ert approved these changes

2022-04-21 09:10 UTC, merged