add NFT detail
DimensionDev/Mask-iOS pull request #25
Opened 2022-02-24 10:25 UTC by hydraCy

2022-02-25 01:55 UTC, sxiaojian88 commented on Maskbook/Scene/Wallet/NFTDetail/NFTActionViewController.swift
> +                       // to do  toast
You can do the toast with Toast.swift

2022-02-25 01:58 UTC, sxiaojian88 commented on Maskbook/Scene/Wallet/NFTDetail/View/NFTActionTableViewCell.swift
> +    static let reuseIdentifier = "NFTActionTableViewCell"
```suggestion
   
```

2022-02-25 03:30 UTC, foxsin10 requested changes

2022-02-25 03:30 UTC, foxsin10 commented on Maskbook/Error/MaskError.swift
> +            let web3error = error as! Web3Error
Avoid force unwrap here, use  `(error as? Web3Error)?.errorDescription  ?? ""` instead.

2022-02-25 03:30 UTC, foxsin10 commented on Maskbook/Scene/Wallet/Balance/View/AccountCardView.swift
> -            UIColor.white.withAlphaComponent(0.08).cgColor,
Conflicts with [this pull request](https://github.com/DimensionDev/Mask-iOS/pull/24)

2022-02-25 08:59 UTC, sxiaojian88 approved these changes

2022-02-28 02:02 UTC, jk234ert commented
@hydraCy plz fix the conflicts

2022-03-01 02:28 UTC, merged