Feat/search nft
DimensionDev/Mask-iOS pull request #253
Opened 2022-08-11 08:47 UTC by hydraCy

2022-08-11 09:48 UTC, foxsin10 requested changes

2022-08-11 09:48 UTC, foxsin10 commented on Maskbook/Scene/Wallet/WalletSend/ViewModel/SearchSingleNFTViewModel.swift
> +        Publishers.CombineLatest(searchString, collectiblesSubject)
```suggestion
        Publishers.CombineLatest(searchString, collectiblesSubject)
            .map { text, collectibles -> [Collectible] in
                guard let text = text,
                      !text.isEmpty else {
                    return collectibles
                }
                
                return collectibles.filter { collectible in
                    guard let name = collectible.name,
                          let tokenID = collectible.tokenId else {
                        return false
                    }

                    if let _ = [name, tokenID].first(where: { $0.containsIgnoreCase(string: text) }) {
                        return true
                    } else {
                        return false
                    }
                }
            }
            .bind(to: \.dataSource, on: self)
            .store(in: &disposeBag)
```

2022-08-11 09:48 UTC, foxsin10 commented on Maskbook/Scene/Wallet/WalletSend/ViewModel/SearchSingleNFTViewModel.swift
> +        Publishers.CombineLatest(searchString, collectiblesSubject)
And we should add `debounce` or `throttle` to searchString publisher

2022-08-11 09:48 UTC, foxsin10 commented on Maskbook/Supporting Files/Coordinator.swift
> +        case let .luckydropSearchNFT(delegate: viewController,contractAddress: address):
```suggestion
        case let .luckydropSearchNFT(selectionDelegate, contractAddress):
```

2022-08-11 09:48 UTC, foxsin10 commented on Maskbook/Supporting Files/Coordinator.swift
> +        case let .luckydropSearchCollection(delegate: viewController):
```suggestion
        case let .luckydropSearchCollection(selectionDelegate):
```

2022-08-11 09:48 UTC, foxsin10 commented on Maskbook/Scene/Wallet/WalletSend/SearchSingleNFTViewController.swift
> +    lazy var searchTextField: MaskTextField = {
```suggestion
    private lazy var searchTextField: MaskTextField = {
```

2022-08-11 09:48 UTC, foxsin10 commented on Maskbook/Scene/Wallet/WalletSend/SearchSingleNFTViewController.swift
> +    lazy var searchTextField: MaskTextField = {
And also apply to all UI components which are not called from outside

2022-08-11 09:48 UTC, foxsin10 commented on Maskbook/Scene/Wallet/WalletSend/SearchNFTCollectionViewController.swift
> +    let searchTextField: MaskTextField = {
```suggestion
    private let searchTextField: MaskTextField = {
```

2022-08-11 09:48 UTC, foxsin10 commented on Maskbook/Scene/Wallet/WalletSend/SearchNFTCollectionViewController.swift
> +    let searchTextField: MaskTextField = {
And also apply to all UI components which are not called from outside

2022-08-11 09:48 UTC, foxsin10 commented on Maskbook/Scene/App/RedPacket/ViewModel/NftLuckyDropViewModel.swift
> +    func returnSelectedNFT(collectible: [Collectible]?){
```suggestion
    func returnSelectedNFT(collectible: [Collectible]?) {
```

2022-08-11 09:48 UTC, foxsin10 commented on Maskbook/Scene/App/RedPacket/ViewModel/NftLuckyDropViewModel.swift
> +    func chooseNFTCollectionAction(token: Collectible){
```suggestion
    func chooseNFTCollectionAction(token: Collectible) {
```

2022-08-12 02:43 UTC, sxiaojian88 commented on CoreDataStack/Entity/Entity+Managed.swift
> +    public class func predicate(address: String, networkId: UInt64, contractAddress: String, enabled: Bool) -> NSPredicate {
```suggestion
    public class func predicate(accountAddress: String, networkId: UInt64, contractAddress: String, enabled: Bool) -> NSPredicate {
```

2022-08-12 03:05 UTC, merged