Fix/mm 348
DimensionDev/Mask-iOS pull request #86
Opened 2022-03-29 08:58 UTC by sxiaojian88

2022-03-29 09:28 UTC, cythb approved these changes

2022-03-30 02:34 UTC, jk234ert requested changes
Layout looks weird in contacts search mode.

2022-03-30 02:34 UTC, jk234ert commented on Maskbook/Extension/UserDefaults+extension.swift
> +        if appVersion != "2.0.0" {
Why check appVersion here?

2022-03-30 06:19 UTC, jk234ert approved these changes

2022-03-30 06:29 UTC, merged